---
- name: Install systemd-journal-gateway 
  yum:
    name: systemd-journal-gateway
    state: installed
    update_cache: yes

- name: Create a /var/log/journal/remote remote directory 
  file:
    path: /var/log/journal/remote
    state: directory
    mode: '0755'
    owner: systemd-journal-remote
    group: systemd-journal-remote

- name: Edit systemd-journal-remote.service unit
  replace:
    path: /lib/systemd/system/systemd-journal-remote.service
    regexp: 'https'
    replace: 'http'

- name: Reload network service
  systemd:
    name: network
    state: started

- name: Run systemd-journal-remote service
  systemd:
    name: systemd-journal-remote
    state: started